dwtc:
  - ","
  - 0
  - 0
  - "CLASS"

PLANNING_plrx:
  - "\t"
  - null
  - null
  - 12

#GERMAN_credit_data:
#  - "\s+"
#  - null
#  - null
#  - 24

FERTILITY:
  - ","
  - 0
  - null
  - "Diagnosis"

PIMA-indians-diabetes:
  - ","
  - 0
  - null
  - "Outcome"

australian:
  - " "
  - null
  - null
  - 14

ILPD_Indian Liver Patient Dataset (ILPD):
  - ","
  - 0
  - null
  - "label"

IONOSPHERE_ionosphere:
  - ","
  - null
  - null
  - 34

HEART:
  - ","
  - 0
  - null
  - "target"

HABERMAN:
  - ","
  - null
  - null
  - 3

BREAST:
  - ","
  - 0
  - null
  - "diagnosis"

DIABETES:
  - ","
  - 0
  - null
  - "Outcome"

abalone:
  - ","
  - 0
  - null
  - "label"

adult:
  - ","
  - 0
  - null
  - "Target"

#wine:
#  - ","
#  - 0
#  - null
#  - "Class"

glass:
  - ","
  - 0
  - null
  - "Type"

#parkinsons:
#  - ","
#  - 0
#  - null
#  - "status"

zoo:
  - ","
  - 0
  - null
  - "class_type"

flag:
  - ","
  - null
  - null
  - 6

anomaly:
  - ","
  - 0
  - null
  - null

automobile:
  - ","
  - 0
  - null
  - "price"

bank:
  - ","
  - 0
  - null
  - "deposit"

bike:
  - ","
  - 0
  - null
  - "cnt"

blood:
  - ","
  - 0
  - null
  - "Class"

boston:
  - ","
  - 0
  - null
  - "medv"

cancer:
  - ","
  - 0
  - null
  - "Class"

concrete:
  - ","
  - 0
  - null
  - "strength"

credit:
  - ","
  - 0
  - null
  - "default"

diabetes:
  - ","
  - 0
  - null
  - "Class variable"

elections:
  - ","
  - 0
  - null
  - null

electrical_grid:
  - ","
  - 0
  - null
  - "stabf"

employee:
  - ","
  - 0
  - null
  - "left"

energy:
  - ","
  - 0
  - null
  - "Heating Load"

#energy:
#  - ","
#  - 0
#  - null
#  - "Cooling Load"

facebook:
  - ","
  - 0
  - null
  - null

forest:
  - ","
  - 0
  - null
  - "area"

gold:
  - ","
  - 0
  - null
  - "Gold_T+22"

heart:
  - ","
  - 0
  - null
  - "DEATH"

heart_disease:
  - ","
  - 0
  - null
  - "Disease"

hepatitis:
  - ","
  - 0
  - null
  - "Class"

house:
  - ","
  - 0
  - null
  - "SalePrice"

income:
  - ","
  - 0
  - null
  - "income >50K"

insurance:
  - ","
  - 0
  - null
  - "charges"

ipl:
  - ","
  - 0
  - null
  - null

iris:
  - ","
  - 0
  - null
  - "species"

jewellery:
  - ","
  - 0
  - null
  - null

juice:
  - ","
  - 0
  - null
  - "Purchase"

mice:
  - ","
  - 0
  - null
  - null

migration:
  - ","
  - 0
  - null
  - null

nba:
  - ","
  - 0
  - null
  - "TARGET_5Yrs"

parkinsons:
  - ","
  - 0
  - null
  - "PPE"

pokemon:
  - ","
  - 0
  - null
  - null

poker:
  - ","
  - 0
  - null
  - "CLASS"

population:
  - ","
  - 0
  - null
  - null

public_health:
  - ","
  - 0
  - null
  - null

questions:
  - ","
  - 0
  - null
  - "Next_Question"

satellite:
  - ","
  - 0
  - null
  - "Class"

seeds:
  - ","
  - 0
  - null
  - null

traffic:
  - ","
  - 0
  - null
  - "traffic_volume"

wholesale:
  - ","
  - 0
  - null
  - null

wine:
  - ","
  - 0
  - null
  - "type"
